# Setup
title:               C# in practice
tagline:             ''
description:         'Here I would like to talk about .net framework focusing mostly on practical things'
url:                 
baseurl:             ''
paginate:            5
paginate_path:       "/blogs/page:num/"


# About/contact
author:
  name:              Alex Kovanev
  url:               
  email:             akovanev@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
